### ISSUE TITLE
Enhance aws_lex_models_v2 documentation

### ISSUE THREAD

**Issue by giach** [aws-beam/aws-erlang#121]
I would like to use the API to create an upload URL using `aws_erlang`. Unfortunately, it's not clear what are the expected parameters for the function

`create_upload_url(Client, Input)`
`Gets a pre-signed S3 write URL that you use to upload the zip archive when importing a bot or a bot locale.`

There might be more functions which require enhanced documentation. Thank you!

**Comment by onno-vos-dev** [comment]
The docs are part of the AWS Go SDK that we generate AWS-Erlang from so adding docs should be done by updating the docs in AWS Go SDK. Once in place, the docs of aws-erlang will be automatically updated.

In this case by updating: [docs-2.json#L19](https://github.com/aws/aws-sdk-go/blob/main/models/apis/models.lex.v2/2020-08-07/docs-2.json#L19)

**Comment by onno-vos-dev** [comment]
Unfortunately we do not control the docs and also the migration to AWS SDK Go V2 (aws-beam/aws-codegen/pull/104) did not improve the documentation on their end so hence the docs remained the same. 

With aws-beam/aws-codegen/pull/109 however the addition of types should hopefully benefit this greatly :-) With that, this particular function (and all others) would get a typespec added to them so that for example the function in question would look like below:

```erlang
%% Example:
%% test_set_import_resource_specification() :: #{
%%   <<"description">> => string(),
%%   <<"importInputLocation">> => test_set_import_input_location(),
%%   <<"modality">> => list(any()),
%%   <<"roleArn">> => string(),
%%   <<"storageLocation">> => test_set_storage_location(),
%%   <<"testSetName">> => string(),
%%   <<"testSetTags">> => map()
%% }
-type test_set_import_resource_specification() :: #{binary() => any()}.

-type create_upload_url_errors() ::
    throttling_exception() | 
    validation_exception() | 
    internal_server_exception() | 
    resource_not_found_exception() | 
    conflict_exception().
 
%% @doc Gets a pre-signed S3 write URL that you use to upload the zip
%% archive when importing a bot or a bot locale.
-spec create_upload_url(aws_client:aws_client(), create_upload_url_request()) ->
    {ok, create_upload_url_response(), tuple()} |
    {error, any()} |
    {error, create_upload_url_errors(), tuple()}.
create_upload_url(Client, Input) ->
    create_upload_url(Client, Input, []).
```

Closing as there really isn't that much more we can do 😢
